### ISSUE TITLE
the performace between one image as input and two images as input?

### ISSUE THREAD

**Issue by LightToYang** [xingyizhou/CenterTrack#18]
CenterNet: one image as input (3 channels)
CenterTrack(detection only): two images as input (6 channels)
No ablation study between these two conditions.

**Comment by LightToYang** [comment]
I think this ablation study can be done on CrowdHuman dataset.

**Comment by xingyizhou** [comment]
Thank you for the suggestions. We have thought about that, the short answer is it does not affect much (<1 MOTA, which is within the random noise) on MOT17 validation set. One reason for not providing this ablation study in paper is we didn't find a good benchmark for this experiment. We can not do it on COCO since no previous frames are available, and MOT and KITTI are too noisy for small improvements.

**Comment by xingyizhou** [comment]
Closing this for now. Feel free to reopen if you have further questions.
