### ISSUE TITLE
The 3d tracking results of nuscenes

### ISSUE THREAD

**Issue by TommyAnqi** [xingyizhou/CenterTrack#30]
Hi,
Thanks for your awesome work, I have install the module and try to run the demo code. But I found the results of output are not as good as you put in the readme. 
Is there any hints or something I need to fix the problem?
![1ddd_pred](https://user-images.githubusercontent.com/24237343/79579018-98fab280-80f9-11ea-93b3-3410f91c2b09.png)
![2ddd_pred](https://user-images.githubusercontent.com/24237343/79579090-b3349080-80f9-11ea-9e90-a949ca241fd1.png)

**Comment by ammaddd** [comment]
I had the same issue

**Comment by xingyizhou** [comment]
Thank you for the excellent question. This is because the original demo was produced for the original nuScenes image coordinate in `1600x900` (we still use an `800x448` input resolution for the network). However when I created the `nuscenes_mini.mp4` for sample demo, I resized the original video to `800x450` to save space (and the network can still take `800x448` as input). This resize makes the default calibration matrix invalid, as it is for `1600x900`. 

A simple fix is to use a half focal length for the `800x450` input. I have added the instruction to the updated readme. It should be able to reproduce the original demo now.

Note that this only affects demo when no camera calibration is provided and we need to use a guessed one. In benchmark testing, the true camera calibration is used.

**Comment by TommyAnqi** [comment]
> Thank you for the excellent question. This is because the original demo was produced for the original nuScenes image coordinate in `1600x900` (we still use an `800x448` input resolution for the network). However when I created the `nuscenes_mini.mp4` for sample demo, I resized the original video to `800x450` to save space (and the network can still take `800x448` as input). This resize makes the default calibration matrix invalid, as it is for `1600x900`.
> 
> A simple fix is to use a half focal length for the `800x450` input. I have added the instruction to the updated readme. It should be able to reproduce the original demo now.
> 
> Note that this only affects demo when no camera calibration is provided and we need to use a guessed one. In benchmark testing, the true camera calibration is used.

It's perfect now，thanks for reply
