### ISSUE TITLE
Few unknown parameters in opt

### ISSUE THREAD

**Issue by rlrahulkanojia** [xingyizhou/CenterTrack#8]
while running the code I came across listed opt declarations which were not available

1) simple_radius ( dataset_generic.py)
2)self.opt.cont_fast_focal_loss. (generic_dataset.py line 384)
3)   self._update_oracle(output, batch, opt)  and oracle map in trainer.py .

I commented on these, so code is running awesomely. But I want to know their purpose.
Please help me with these.

**Comment by xingyizhou** [comment]
Thank you for noting this. These are experimental parameters that are not used in the final version. I have removed them in the latest commit. Please don't mind them. For whom that are curious about them, they are:
  - simple_radius: a simplified version of get_radius, which involves solving a quadratic equation for 3 cases. See [here](https://github.com/princeton-vl/CornerNet/issues/110). The simple version works as good as the original version for detection. I didn't release the simplified version because the models in the model zoo are trained using the original version.
  - cont_fast_focal_loss: a modified focal loss that applies soft positive loss on all output pixels (the current version only applies positive loss on center pixels). It works considerably worse than the current version.
  - *oracle: used for the upper bound analysis in [CenterNet supplementary](https://arxiv.org/abs/1904.07850). We didn't do this for CenterTrack.
